### PR TITLE
3616-Uncategorized GB Items should not be counted

### LINKED ISSUE #3616: Category Grade Incorrect when Uncategorized present in Student Review Mode
This is within 11.x, as I can't test master at the moment (due to #3602 ).

When a Gradebook is set up with Categories and has items with point values which are uncategorized, the uncategorized items get counted as part of other categories on the Student Review Mode (backed by StudentGradeSummaryGradesPanel.java). This causes the category score to be incorrect.

See the following screenshots:
Gradebook view

Grade Summary - Correct:
Grade Summary - Correct

Student  Review Mode - Incorrect
Student Review Mode - Incorrect

### PR DESCRIPTION
**Pull request by master-bob**
This causes any assignment which is uncategorized (that is a null
category) to not be included in the category grade calculation.

This resolves #3616 .

### CODE REVIEW

File: edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java [hunk 1]
```diff
@@ -3185,7 +3185,10 @@ private Double calculateCategoryScore(String studentUuid, Long categoryId, List<
 			Assignment assignment = gradeRecord.getAssignment();
 						
 			// remove if not for this category (rule 1)
-			if(assignment.getCategory() != null && categoryId.longValue() != assignment.getCategory().getId().longValue()){
+			if(assignment.getCategory() == null){
+				return true;
+			}
+			if(categoryId.longValue() != assignment.getCategory().getId().longValue()){
```
Comment (ottenhoff) [inline edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java]: Is this comparison of long value equality correct?

http://docs.oracle.com/javase/1.5.0/docs/api/java/lang/Long.html#equals%28java.lang.Object%29

Comment (master-bob) [inline edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java]: longValue() returns a long. Both categoryID and assignemnt.getCategory are not null, so we then have a long != long comparison. So I believe that they would be equality correct, that is this statement and `categoryId.equals(assignment.getCategory().getId())` should be equivalent.
